project:
  type: website
  output-dir: docs

website:
  title: "Andrew Grogan-Kaylor"
  twitter-card: true
  open-graph: true
  favicon: logo.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://ssw.umich.edu/sites/default/files/documents/faculty/cvs/agrogan_cv.pdf
        text: CV
      - text: "Research"
        menu:
          - text: "About My Research"
            href: about-research.qmd
          - text: "Research Papers and Projects"
            href: research.qmd
      - teaching.qmd  
      - text: "Other Projects"
        menu: 
          - text: "Corporal Punishment Bans"
            href: CPbans.qmd
          - text: "Multilevel Workshop"
            href: https://agrogan1.github.io/multilevel-workshop/
          - text: "Global Families"
            href: https://globalfamilies.quarto.pub/global-families-project/
          - text: "Mapping/GIS" 
            href: https://agrogan1.github.io/mapping/
      - text: "Blog-ish Posts"
        menu: 
          - text: Blog
            href: blog.qmd  
          - text: Multilevel Thinking
            href: https://agrogan1.github.io/posts/multilevel-thinking/
          - text: Be Less Wrong
            href: https://agrogan1.github.io/posts/be-less-wrong/index.html
          - text: Multiple Principled Solutions
            href: https://agrogan1.github.io/posts/multiple-principled-solutions/index.html
      - about.qmd

bibliography: agrogan.bib

csl: apa.csl

google-scholar: true

format:
  html:
    theme: [yeti, theme-light.scss]
    mermaid: 
      theme: default
    css: agrogan.css
    lightbox: true
    toc: true
    execute:
      echo: false
      warning: false
      freeze: auto


